databases:
  mongodb:
    uri: 'mongodb://0.0.0.0:27017'
  redis:
    uri: 'redis://0.0.0.0:6379'

factions:
  naming:
    min_faction_name: 2
    max_faction_name: 24
    disallowed_names:
      - nigger
      - nigga
      - nigs
      - palace
      - spawn
  reinvites: 5
  limits:
    max_faction_size: 30
    classes:
      archer: 2
      bard: 1
      rouge: 2,
      miner: 30
  power:
    player_power_value: 0.4
    power_tick_interval: 60
    power_tick_player_modifier: 1
    power_loss_reductions:
      nether: true
      end: true
  ratings:
    challenger: 10000
    diamond: 8000
    platinum: 6000
    gold: 4000
    silver: 2000
    bronze: 1000
  claiming:
    min_claim_size: 8
    max_claims: 3
    block_value: 10.0
    refunded_percent: 0.75
    default_buffers:
      server_faction_build: 16
      server_faction_claim: 32
      player_faction_claim: 1
  timers:
    attacker_tag_duration: 30
    attacked_tag_duration: 10
    enderpearl_duration: 16
    crapple_duration: 5
    gapple_duration: 3600
    totem_duration: 3600
    stuck_duration: 60
    rally_duration: 5
    freeze_duration: 1800
    home_duration: 10
    protection:
      sotw: 3600
      normal: 1800
  spawns:
    overworld_spawn:
      x: 0.0
      y: 64.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
      world: 'world'
    end_spawn:
      x: 0.0
      y: 64.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
      world: 'world_the_end'
    end_exit:
      x: 250.0
      y: 64.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
      world: 'world'

deathbans:
  enabled: true
  standalone: true
  max_durations:
    sotw: 300
    normal: 86400
  min_duration: 30
  life_use_delay: 60
  shop_url: "https://hcfactions.gg/shop"

scoreboard:
  title: '&6&lHCFRevival &c[Map #]'

stats:
  map_number: 0.5

economy:
  starting_balance: 100.0

server_state:
  current_state: 'normal'
  eotw:
    border_shrink_radius: 100.0
    border_shrink_rate: 14400